import type { Metadata } from "next";
import {
  Typography,
  Container,
  Paper,
} from "@mui/material";
import { LoginForm } from "@/components";

export const metadata: Metadata = {
  title: "Frontend Repository - Ebuddy",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <Container maxWidth="xs">
      <Paper elevation={3} sx={{ p: 3, mt: 8, textAlign: "center" }}>
        <Typography variant="h5" gutterBottom>
          Login
        </Typography>
        <LoginForm />
      </Paper>
    </Container>
  );
}
