import type { Metadata } from "next";
import {
  Typography,
  Container,
  Divider,
} from "@mui/material";
import { UserList } from "@/components";

export const metadata: Metadata = {
  title: "User List - Ebuddy",
  description: "Generated by create next app",
};

export default function Users() {
  return (
    <Container style={{ paddingTop: 20, paddingBottom: 20 }}>
      <Divider style={{ marginBottom: 20 }}>
        <Typography variant="h5" gutterBottom>
          User List
        </Typography>
      </Divider>
      <UserList />
    </Container>
  );
}
